version: '3.4'
services:
    wag-docker:
        image: wagvpn/wag
        container_name: wag0
        env_file:
          - .env
        build:
          context: .
          args:
            WEB_USER: ${WEB_USER}
            WEB_PWD: ${WEB_PWD}
        ports:
          - '10180:10180/tcp'
          - '10100:10100/tcp'
          - '10101:10101/tcp'
          - '10321:10321/udp'
        cap_add:
          - NET_ADMIN
          - NET_RAW
          - SYS_ADMIN
        ulimits:
# see PR #1
          memlock: -1
          nofile:
            soft: "65536"
            hard: "65536"
# tests with complete reg/auth didn't require privileged, so it is optional
#        privileged: true
        volumes:
          - './cfg:/cfg:z'
          - './data:/data:z'
        networks:
          - wag
networks:
  wag:
    name: wag